controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

recette_index:
    path: /recettes
    controller: App\Controller\RecetteController::index
    
app_home:
    path: /
    controller: App\Controller\HomeController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_register:
    path: /register
    controller: App\Controller\SecurityController::register

recette_show:
    path: /recette/{id}
    controller: App\Controller\RecetteController::show